// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function minus(a, b) {
  return a - b | 0;
}

function minus_2(a, b) {
  return a - b | 0;
}

var v2 = 10.1;

exports.v2      = v2;
exports.minus   = minus;
exports.minus_2 = minus_2;
/* No side effect */
