// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Test2 = require("./api/Test2.js");

function _private(a, b) {
  return (a + b | 0) + 2 | 0;
}

function add1(a, b) {
  return (a + b | 0) + 2 | 0;
}

function constant1() {
  return 1;
}

var v1 = "aaa";

var func1 = Test2.minus;

exports.v1        = v1;
exports.func1     = func1;
exports._private  = _private;
exports.add1      = add1;
exports.constant1 = constant1;
/* No side effect */
